### ISSUE TITLE
tor version inside container is out of date

### ISSUE THREAD

**Issue by nexus-uw** [TheZ3ro/docker-tor-relay#2]
from the start up logs
```
[warn] Please upgrade! This version of Tor (0.2.8.12) is not recommended, according to the directory authorities. Recommended versions are: 0.2.5.14,0.2.8.14,0.2.9.11,0.3.0.9,0.3.0.10,0.3.1.5-alpha,0.3.1.6-rc
```

is there someway to update the tor version inside the container? if not, could you have docker hub rebuild the container?

**Comment by TheZ3ro** [comment]
The dockfile in this repo needs an update. Tor package is downloaded from the repository. I need to look into this a little bit more

**Comment by TheZ3ro** [comment]
The project is now unmaintained since https://hub.docker.com/r/jess/tor-relay/ is equivalent and updated (source code here https://github.com/jessfraz/dockerfiles/tree/master/tor-relay)

I've updated the readme to state the announcement.
